apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: apache
spec:
  replicas: 5
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: mydeploymentcont
        image: pra5anth/pras/new:latest
        ports:
        - containerPort: 80
